<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HealthResponse</code>
 */
class HealthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isActive = 1;</code>
     */
    private $isActive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isActive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isActive = 1;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Generated from protobuf field <code>bool isActive = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->isActive = $var;

        return $this;
    }

}

