<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace GPBMetadata;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8020a096170692e70726f746f22070a05456d70747922320a044e6f74" .
            "65120a0a026964180120012809120d0a057469746c65180220012809120f" .
            "0a07636f6e74656e7418032001280922240a0c4e6f7465526573706f6e73" .
            "6512140a056e6f74657318012003280b32052e4e6f7465221b0a0d4e6f74" .
            "65526571756573744964120a0a02696418012001280932c2010a0a415049" .
            "5365727669636512240a094c6973744e6f74657312062e456d7074791a0d" .
            "2e4e6f7465526573706f6e7365220012260a0b4765744e6f746542794964" .
            "120e2e4e6f74655265717565737449641a052e4e6f74652200121c0a0a43" .
            "72656174654e6f746512052e4e6f74651a052e4e6f74652200121c0a0a55" .
            "70646174654e6f746512052e4e6f74651a052e4e6f74652200122a0a0e44" .
            "656c6574654e6f746542794964120e2e4e6f74655265717565737449641a" .
            "062e456d7074792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

