<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

namespace GPBMetadata;

class Health
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a0c6865616c74682e70726f746f22070a05456d70747922220a0e48" .
            "65616c7468526573706f6e736512100a0869734163746976651801200128" .
            "0832360a0d4865616c74685365727669636512250a084973416374697665" .
            "12062e456d7074791a0f2e4865616c7468526573706f6e73652200620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

